
name = "cool-blog"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

# Pages configuration
pages_build_output_dir = ".next"

[vars]
NODE_ENV = "production"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "preview" }

[env.development]
vars = { NODE_ENV = "development" }

# Configure for Next.js compatibility
[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

# Environment variables (configure these in Cloudflare dashboard)
# DATABASE_URL = "your_database_url_here"
