name = "cool-blog"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".next"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "preview" }

# Note: redirects should be handled via _redirects file
